"""
Given: A DNA string s of length at most 1000 nt.
Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
"""
string = 'CCATAAACCGAGGCGGGTGTTGCAAATGCTTTATCACTTTCTGGGTTAGTTCGAAGGTTTGAGATGAAATAAGTTCTACGCTCTGAAGAGAGAATTACCTATAGGTAAGCCTGAAGAAACCAGTTTGCTAGTATTACTCTTCGG' \
         'AGTAATACGAAAATCACGAACGCGCATGTAGTTCGCTGTCGGTCTTACCGTGTAACATCTAGGGCCGCGTGAATCGGTTCCCATAAAGTGTGCGAAGAGGCGTGAGATGGACAGCACTCAGTAGGGATCTTATAATTCGCGGA' \
         'CTTCACGGGTAGTTCGAGTCTAGTGGTATGGTTGTATCGTTCCGGGTGATTGGGGCGCACGAACCCTTGGACGTGATAAGGGGTCTGGTCTCTCTAGGCGGCATGCTGTTCATAGCACAAGTTCACAACCTTGTAGTAGGCA' \
         'TGTACTTGTAGGTCCACACGTGTGTCCCTTGGTCGTGGATGCCGCTTAGATCCATGGTTCATGGAGGGTGATCGTGGGCTATGTCGAAGCTTTACGATTTAGTACCGGAAGAGTGACGTTAGCACGACTCATCCTCTGGCCT' \
         'ACGCCTCGCCACGATGATTCCGTTCCTTTGCTATTGCAACCGGCCCTTGCGCATGTCACAATTCGATCCGTGTGTTGAATCCTATCAAAGGTGTCTAGTGAATGTCTTCCATCGCTTTGGCACGACGCCTGCTAGTGTAAC' \
         'ATGGAGTACCGTAAGCCAGCCTTAGACCCGTCTTGAATGTTCGGATATCACAAATAAGTCCGTCGGTATATGAATGGACCCCTATGTTTGGCAAGATGACACCTAGTCTGATTTCCGGATATCATACCTCAACGTTCGAGT' \
         'TAAATTCGGGCCCTATGCCATCGAAGCACGGGGGTCGAGTCGATCTGC '

def count_nucleotides(dna):
    dna = list(dna)
    return dna.count('A'), dna.count('C'), dna.count('G'), dna.count('T')


# from timeit import default_timer as timer
#
# start = timer()
# count_nucleotides(string)
# end = timer()
# print(abs(start - end))
# # returns in 5.0x10^-5 seconds
#
# # more efficient to call count directly on a string without converting to a list first
# def qt(s):
#     return s.count("A"), s.count("G"), s.count("C"), s.count("T")
#
# start = timer()
# qt(string)
# end = timer()
# print(abs(start - end))
# returns in 1.0x10^-5 seconds
